server:
  port: 8099

#yandexProperties:
#  endpointUrl: https://test-fav-list-storage.storage.yandexcloud.net/
#  bucketName: test-fav-list-storage
#  endpointUrl: https://favlist.storage.yandexcloud.net/
#  bucketName: favlist

#  accessKey: eGM6uE-68_Fn5rAStbLX
#  secretKey: jrsGqUFK_jZbcsAcW_0Jr8avhqgMgXQG7Dy3GQbL
#  serviceEndpoint: storage.yandexcloud.net
#  signingRegion: ru-central1

spring:
  mail:
    host: smtp.gmail.com
    username: app.fav.list@gmail.com
    password: adwpaqxikpgphsrb
    port: 587
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  datasource:
    url: jdbc:postgresql://${CLEARDB_DATABASE_URL}:5432/d9l48qg79r5pma
    username: ysiuwavkrlrgbs
    password: ab334deaf5b0f68471c88c27b052550ec24c9791b8a5ff59524655b476b938f8
#    url: jdbc:postgresql://${CLEARDB_DATABASE_URL}:5432/postgres
#    username: postgres
#    password: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 1057678439553-qaqo12dndq78l320kb2sgsi2h6n2720t.apps.googleusercontent.com
#            clientSecret: RWfOIpHAN1K2gQic3SeP0SVk
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile
#          facebook:
#            clientId: 1095809287482215
#            clientSecret: c3028ff6a155070d21d778bc7a3303d3
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - public_profile
#        provider:
#          facebook:
#            authorizationUri: https://www.facebook.com/v7.0/dialog/oauth
#            tokenUri: https://graph.facebook.com/v7.0/oauth/access_token
#            userInfoUri: https://graph.facebook.com/v7.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 8640000000
#  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth2/redirect
#      - http://favlist.net/oauth2/redirect
#      - https://favlist.net/oauth2/redirect
#      - myandroidapp://oauth2/redirect
#      - myiosapp://oauth2/redirect