server:
  port: 8099

spring:
  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    port: 587
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  datasource:
    url: jdbc:postgresql://${CLEARDB_DATABASE_URL}:5432/${DATABASE}
    username: ${USER}
    password: ${PASSWORD}
#    url: jdbc:postgresql://${CLEARDB_DATABASE_URL}:5432/postgres
#    username: postgres
#    password: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

app:
  auth:
    tokenSecret: ${TOKENSECRET}
    tokenExpirationMsec: 8640000000
